### ISSUE TITLE
Missing styling

### ISSUE THREAD

**Issue by caneledip** [Thanawas-Sirilertsathit/ku-polls#47]
I follow your installation instruction. The application run fine, but I didn't get my page to look the same as in your README.md example. Log always show a warning
```
WARNING 2024-09-14 21:03:38,366 log Not Found: /static/polls/style.css
WARNING 2024-09-14 21:03:38,366 basehttp "GET /static/polls/style.css HTTP/1.1" 404 179
```

**Comment by Thanawas-Sirilertsathit** [comment]
can you try it again and run the most bottom command in the Installation.md I just add?

**Comment by Thanawas-Sirilertsathit** [comment]
python manage.py collectstatic

**Comment by Thanawas-Sirilertsathit** [comment]
tell me if it works or not
